export { default as Company } from './company/Company';
export { default as AboutUs } from './company/about us/AboutUs';
export { default as Blockchain } from './services/pages/blockchain/Blockchain';
export { default as ContactUs } from './contact us/ContactUs';
export { default as HireADeveloper } from './hire developer/HireADeveloper';
export { default as Services } from './services/Services';
export { default as CyberSecurity } from './services/pages/cyber security/CyberSecurity';
export { default as DataScience } from './services/pages/data science/DataScience';
export { default as Ecommerce } from './services/pages/e-commerce/Ecommerce';
export { default as OnlineMarket } from './services/pages/online market places/OnlineMarket';
export { default as HireTeams } from './solutions/product development services/HireTeams';
export { default as Header } from './header/Header';
export { default as Footer } from './footer/Footer';
export { default as Testimonials } from './Testimonials';
export { default as CTA } from './CTA';
export { default as PortfolioPage } from './company/Portfolio/PortfolioPage';
export { default as IndustryExpertise } from './IndustryExpertise';
export { default as OurExperties } from './OurExperties';
export { default as OCFramwork } from './OCFramework';
export { default as WCTechilab } from './WCTechilab';
export { default as FAQDisclosure } from './FAQDisclosure';
export { default as MainSection } from './MainSection';
export { default as BuildForYou } from './BuildForYou';